@api = http://localhost:9090

### get clients
GET {{api}}/biz/ws/clients

### boardcast message
POST {{api}}/biz/ws/broadcast
Content-Type: application/json

{
    "namespace": "foo",
    "payload": "demo-data"
}

### send message
POST {{api}}/biz/ws/send
Content-Type: application/json

{
    "namespace": "foo",
    "sender": "abc",
    "receiver": ["123"],
    "payload": "demo-data2"
}